import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import { Script } from "node:vm";
import ts from "typescript";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";

const path = resolve("components/cbt-exam-ui.tsx");
const output = ts.transpileModule(readFileSync(path, "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX, target: ts.ScriptTarget.ES2022 } }).outputText;
const module = { exports: {} };
new Script(`(function(require,module,exports){${output}\n})`).runInThisContext()(createRequire(path), module, module.exports);
const { toggleAnswerSelection, AnswerChoices, MockExamGuide } = module.exports;

const original = { q1: 0, q2: 3 };
const selected = toggleAnswerSelection(original, "q3", 2);
assert.deepEqual(selected, { q1: 0, q2: 3, q3: 2 });
assert.deepEqual(original, { q1: 0, q2: 3 }, "Editing another row must not mutate earlier answers");
assert.deepEqual(toggleAnswerSelection(selected, "q3", 1), { q1: 0, q2: 3, q3: 1 });
assert.deepEqual(toggleAnswerSelection(selected, "q3", 2), original);
assert.equal(Object.keys(toggleAnswerSelection(selected, "q3", 2)).length, 2, "Deselect must update the answered count");
assert.deepEqual(toggleAnswerSelection({}, "q1", 0), { q1: 0 }, "The first choice must count as an answer");

const html = renderToStaticMarkup(React.createElement(AnswerChoices, { number: 12, selected: 2, disabled: false, onSelect() {} }));
assert.equal((html.match(/role="radio"/g) || []).length, 4);
assert.equal((html.match(/aria-checked="true"/g) || []).length, 1);
assert.match(html, /aria-label="12번 문항 ③번 보기"/);
assert.equal((html.match(/tabindex="0"/g) || []).length, 1);
const disabled = renderToStaticMarkup(React.createElement(AnswerChoices, { number: 12, selected: 2, disabled: true, onSelect() {} }));
assert.equal((disabled.match(/disabled=""/g) || []).length, 4);
const five = renderToStaticMarkup(React.createElement(AnswerChoices, { number: 5, count: 5, selected: 4, disabled: false, onSelect() {} }));
assert.equal((five.match(/role="radio"/g) || []).length, 5);
assert.match(five, /aria-label="5번 문항 ⑤번 보기"/);
const guide = renderToStaticMarkup(React.createElement(MockExamGuide, { name: "수험자", onStart() {} }));
assert.match(guide, /1\/4/);
assert.doesNotMatch(guide, /20261001-12345|@/);

// Render the authenticated list without executing effects or contacting a DB.
const clientPath = resolve("components/question-bank-client.tsx");
const clientOutput = ts.transpileModule(readFileSync(clientPath, "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX, target: ts.ScriptTarget.ES2022 } }).outputText;
const client = { exports: {} };
const clientRequire = (name) => {
  if (name === "next/navigation") return { useRouter: () => ({}) };
  if (name === "next/link") return { default: ({ href, children, ...props }) => React.createElement("a", { href, ...props }, children) };
  if (name === "@/components/cbt-exam-ui") return module.exports;
  if (name === "@/components/logo") return { CbtMateLogo: () => null };
  if (name === "@/components/site-header") return { SiteHeader: () => null };
  if (name === "@/components/ai-question-explanation") return { AiQuestionExplanation: () => null };
  if (name === "@/components/cbt-question-review") return { QuestionResponseStats: () => null, QuestionMemo: () => null };
  if (name === "@/components/question-bank-loading") return { QuestionBankLoading: () => null };
  if (name === "@/components/question-answer-info") return { QuestionAnswerInfo: () => null };
  if (name === "@/components/question-body") return { QuestionBody: ({ question }) => React.createElement("h1", null, question.stem) };
  if (name === "@/components/question-choice-content") return { QuestionChoiceContent: ({ choice }) => React.createElement("span", null, choice.text) };
  if (name.startsWith("@/lib/")) return { certSlug: (cert) => cert.name };
  return createRequire(clientPath)(name);
};
new Script(`(function(require,module,exports){${clientOutput}\nexports.LearningScreen=LearningScreen;})`).runInThisContext()(clientRequire, client, client.exports);
const questions = Array.from({ length: 25 }, (_, i) => ({ id: `q${i}`, certId: "test", subjectId: "test", no: i + 1, stem: `검증용 문항 ${i + 1}` }));
const wrongNotes = Object.fromEntries(questions.map((question) => [question.id, { wrongCount: 3, lastWrongAt: "2026-10-01T00:00:00Z", memo: "", mastered: false }]));
questions.unshift({ id: "memo-only", certId: "test", subjectId: "test", no: 0, stem: "정답 메모 전용 문항" });
wrongNotes["memo-only"] = { wrongCount: 0, lastWrongAt: "2026-10-05T00:00:00Z", memo: "맞힌 문제의 메모", mastered: false };
const list = renderToStaticMarkup(React.createElement(client.exports.LearningScreen, { mode: "wrong-notes", dataset: { certs: [{ id: "test", name: "검증용 종목" }], subjects: [{ id: "test", certId: "test", name: "검증용 과목" }], questions }, store: { attempts: [], bookmarks: [], wrongNotes }, user: {}, authReady: true, saveStore() { throw new Error("Rendering must not write data"); } }));
assert.equal((list.match(/class="cbt-learning-row cbt-wrong-row"/g) || []).length, 20);
assert.equal((list.match(/type="checkbox"/g) || []).length, 20);
assert.doesNotMatch(list, /<textarea/);
assert.doesNotMatch(list, /정답 메모 전용 문항/, "Memo-only questions must not appear as wrong answers");
assert.match(list, /많이 틀린 순/);
assert.match(list, /20문항 풀기/);
console.log("CBT UI OK: answer selection/change/deselect, isolation, counters, radio semantics, locked controls, guide identity, 20-row paging, collapsed memos, sort controls; no DB writes");
