create extension if not exists pgcrypto;
create table if not exists public.question_bank_certs (id uuid primary key default gen_random_uuid(), name text not null unique, created_at timestamptz not null default now());
create table if not exists public.question_bank_subjects (id uuid primary key default gen_random_uuid(), cert_id uuid not null references public.question_bank_certs(id) on delete cascade, name text not null, created_at timestamptz not null default now(), unique(cert_id,name));
create table if not exists public.question_bank_exams (id uuid primary key default gen_random_uuid(), cert_id uuid not null references public.question_bank_certs(id) on delete cascade, year int not null, round text not null, title text not null, duration_minutes int not null default 60 check(duration_minutes > 0), pass_score numeric(5,2) not null default 60, question_count int not null default 0, created_at timestamptz not null default now(), unique(cert_id,year,round));
create table if not exists public.question_bank_import_batches (id uuid primary key default gen_random_uuid(), file_name text not null, status text not null default 'needs_review' check(status in ('needs_review','published','rolled_back')), row_count int not null default 0, error_count int not null default 0, created_by uuid references auth.users(id), created_at timestamptz not null default now(), rolled_back_at timestamptz);
create table if not exists public.question_bank_questions (id uuid primary key default gen_random_uuid(), exam_id uuid not null references public.question_bank_exams(id) on delete cascade, cert_id uuid not null references public.question_bank_certs(id) on delete cascade, subject_id uuid references public.question_bank_subjects(id) on delete set null, no int not null, stem text not null, images jsonb not null default '[]'::jsonb, choices jsonb not null default '[]'::jsonb, answer int not null, explanation text not null default '', status text not null default 'needs_review' check(status in ('draft','needs_review','published')), source_hash text not null unique, import_batch_id uuid references public.question_bank_import_batches(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.question_bank_attempts (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null, config jsonb not null, question_ids jsonb not null default '[]'::jsonb, answers jsonb not null default '{}'::jsonb, started_at timestamptz not null default now(), end_at timestamptz, submitted_at timestamptz, score numeric(5,2), status text not null default 'in_progress' check(status in ('in_progress','submitted')));
create table if not exists public.question_bank_wrong_notes (user_id uuid not null references auth.users(id) on delete cascade, question_id uuid not null references public.question_bank_questions(id) on delete cascade, wrong_count int not null default 1, last_wrong_at timestamptz not null default now(), memo text not null default '', mastered boolean not null default false, primary key(user_id,question_id));
create table if not exists public.question_bank_bookmarks (user_id uuid not null references auth.users(id) on delete cascade, question_id uuid not null references public.question_bank_questions(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id,question_id));
create table if not exists public.question_bank_presets (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, config jsonb not null, created_at timestamptz not null default now());
create index if not exists question_bank_questions_exam_idx on public.question_bank_questions(exam_id,no);
create index if not exists question_bank_questions_status_idx on public.question_bank_questions(status);
create index if not exists question_bank_attempts_user_idx on public.question_bank_attempts(user_id,started_at desc);
alter table public.question_bank_certs enable row level security;
alter table public.question_bank_subjects enable row level security;
alter table public.question_bank_exams enable row level security;
alter table public.question_bank_questions enable row level security;
alter table public.question_bank_import_batches enable row level security;
alter table public.question_bank_attempts enable row level security;
alter table public.question_bank_wrong_notes enable row level security;
alter table public.question_bank_bookmarks enable row level security;
alter table public.question_bank_presets enable row level security;
create policy "question certs readable" on public.question_bank_certs for select using (true);
create policy "question subjects readable" on public.question_bank_subjects for select using (true);
create policy "question exams readable" on public.question_bank_exams for select using (true);
create policy "published questions readable" on public.question_bank_questions for select using (status='published');
create policy "users read own attempts" on public.question_bank_attempts for select using (auth.uid()=user_id);
create policy "users create attempts" on public.question_bank_attempts for insert with check (auth.uid()=user_id or user_id is null);
create policy "users update attempts" on public.question_bank_attempts for update using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "users manage wrong notes" on public.question_bank_wrong_notes for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "users manage bookmarks" on public.question_bank_bookmarks for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "users manage presets" on public.question_bank_presets for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
